# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_ask1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(665, 563)
        self.ADD = QtWidgets.QPushButton(Dialog)
        self.ADD.setGeometry(QtCore.QRect(550, 520, 93, 28))
        self.ADD.setObjectName("ADD")
        self.SUB = QtWidgets.QPushButton(Dialog)
        self.SUB.setGeometry(QtCore.QRect(430, 520, 93, 28))
        self.SUB.setObjectName("SUB")
        self.MOVE = QtWidgets.QPushButton(Dialog)
        self.MOVE.setGeometry(QtCore.QRect(310, 520, 93, 28))
        self.MOVE.setObjectName("MOVE")
        self.text_input_1 = QtWidgets.QTextEdit(Dialog)
        self.text_input_1.setGeometry(QtCore.QRect(30, 50, 104, 87))
        self.text_input_1.setObjectName("text_input_1")
        self.text_input_2 = QtWidgets.QTextEdit(Dialog)
        self.text_input_2.setGeometry(QtCore.QRect(190, 50, 104, 87))
        self.text_input_2.setObjectName("text_input_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(200, 20, 55, 16))
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(460, 40, 160, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RejA = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.RejA.setObjectName("RejA")
        self.verticalLayout.addWidget(self.RejA)
        self.RejB = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.RejB.setObjectName("RejB")
        self.verticalLayout.addWidget(self.RejB)
        self.RejC = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.RejC.setObjectName("RejC")
        self.verticalLayout.addWidget(self.RejC)
        self.RejD = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.RejD.setObjectName("RejD")
        self.verticalLayout.addWidget(self.RejD)
        self.save = QtWidgets.QPushButton(Dialog)
        self.save.setGeometry(QtCore.QRect(20, 460, 93, 28))
        self.save.setObjectName("save")
        self.load = QtWidgets.QPushButton(Dialog)
        self.load.setGeometry(QtCore.QRect(20, 500, 93, 28))
        self.load.setObjectName("load")
        self.CzyKrokowa = QtWidgets.QCheckBox(Dialog)
        self.CzyKrokowa.setGeometry(QtCore.QRect(470, 280, 81, 20))
        self.CzyKrokowa.setObjectName("CzyKrokowa")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ADD.setText(_translate("Dialog", "Dodawanie"))
        self.SUB.setText(_translate("Dialog", "Odejmowanie"))
        self.MOVE.setText(_translate("Dialog", "Przeniesienie"))
        self.label.setText(_translate("Dialog", "Input 1"))
        self.label_2.setText(_translate("Dialog", "Input 2"))
        self.RejA.setText(_translate("Dialog", "Rejestr AX"))
        self.RejB.setText(_translate("Dialog", "Rejestr BX"))
        self.RejC.setText(_translate("Dialog", "Rejestr CX"))
        self.RejD.setText(_translate("Dialog", "Rejestr Dx"))
        self.save.setText(_translate("Dialog", "Zapisz"))
        self.load.setText(_translate("Dialog", "Wczytaj"))
        self.CzyKrokowa.setText(_translate("Dialog", "PracaKrokowa"))


